[package]
name = "pspsdk-macros"
authors = ["GrayJack <gr41.j4ck@gmail.com>"]
version = "0.0.1"
license = "MPL-2.0-no-copyleft-exception"
edition = "2024"
repository = "https://github.com/GrayJack/pspsdk-rs"
description = "Procedural macros for the pspsdk crate"
categories = ["embedded", "rust-patterns"]
keywords = ["psp", "pspsdk", "sdk", "macro"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "3", features = [
    "clone-impls",
    "full",
    "parsing",
    "printing",
    "proc-macro",
], default-features = false }
quote = { version = "1", default-features = false }
proc-macro2 = "1"
sha1 = "0.11.0"

[features]
