[package]
name = "pspsdk"
authors = ["GrayJack <gr41.j4ck@gmail.com>"]
version = "0.1.0"
edition = "2024"

[dependencies]
bitflag-attr = { version = "0.13.0", features = ["const-mut-ref"] }
pspsdk-macros = { path = "pspsdk-macros", features = [] }

[features]
default = ["non-stub-code"]
# Enable kernel modules.
kernel = []
# Enable CFW modules.
cfw-api = []

# Build with std support
std = []

# Includes code that is not stub definition.
#
# Compile this library without this feature to have it as a stub provider.
# Useful to compile this as a static library for other projects.
non-stub-code = []

# For the following features, you can't enable more than one of them
# Also, they are more beneficial for CFW implementation, as the SystemControl
# CFW module requires the NIDs to be correct.
#
# For plugins and homebrew apps, they are never required as most moderns CFWs
# implement NID translation table for non-SystemControl modules.
#
# It may be required for signed homebrew apps (homebrew that works on OFW), but
# that is an edge case.

# Use PSP 1.00~3.73 NID on kernel modules
psp_100 = []
# Use PSP 3.80~3.93 NID on kernel modules
psp_380 = []
# Use PSP 3.95~4.05 NID on kernel modules
psp_395 = []
# Use PSP 4.20~4.21 NID on kernel modules
psp_420 = []
# Use PSP 5.00~5.55 NID on kernel modules
psp_500 = []
# Use PSP 5.70 NID on kernel modules
psp_570 = []
# Use PSP 6.00~6.20 NID on kernel modules
psp_600 = []
# Use PSP 6.30~6.39 NID on kernel modules
psp_630 = []
# Use PSP 6.60~6.61 NID on kernel modules (6.61 didn't change NID of exported items)
psp_660 = []
# Use PSPemu 3.65 NID on kernel modules
vita_365 = ["psp_660"]

[workspace]
exclude = ["cargo-pspbuild"]
