[package]
name = "pspsdk"
authors = ["GrayJack <gr41.j4ck@gmail.com>"]
version = "0.1.0"
edition = "2024"

[dependencies]
bitflag-attr = { version = "0.13.0", features = ["const-mut-ref"] }
pspsdk-macros = { path = "pspsdk-macros", features = ["use_crate"] }

[features]
# Enable kernel modules.
kernel = []

# For the following features, you can't enable more than one of them
# Also, they are more beneficial for CFW implementation, as the SystemControl
# CFW module requires the NIDs to be correct.
#
# For plugins and homebrew apps, they are never required as most moderns CFWs
# implement NID translation table for non-SystemControl modules.
#
# It may be required for signed homebrew apps (homebrew that works on OFW), but
# that is an edge case.

# Use PSP 1.50 NID on kernel modules
psp_150 = []
# Use PSP 6.60/6.61 NID on kernel modules (6.61 didn't change NID of exported items)
psp_660_661 = []
# Use PSPemu 3.65 NID on kernel modules
vita_365 = []
# Use a hybrid of PSPemu 3.65 and PSP 6.60/6.61 NID on kernel modules based on Adrenaline used modules
vita_epi = []

[workspace]
members = ["pspsdk-macros"]
