[build]
rustflags = ["-Zthreads=8"]
rustdocflags = [
    "-Zunstable-options",
    "--show-type-layout",
    "--enable-index-page",
]

# [unstable]
# build-std = [
#     "core",
#     "alloc",
#     "compiler_builtins",
#     "panic_unwind",
#     "panic_abort",
#     # "std",
# ]
