[package]
name = "psp-prx-barebones"
version = "0.1.0"
edition = "2024"

# Recommend profile configuration.
# Commented because on workspace, that is configured on the workspace Cargo.toml
# If you are copying the project to bootstrap a PSP project, uncomment these for
# smaller size

# [profile.dev]
# opt-level = "s"

# [profile.release]
# opt-level = "s"
# lto = "thin"
# panic = "abort"

[dependencies]
pspsdk = { path = "../../pspsdk" }
