#![no_std]
#![allow(internal_features)]
#![feature(rustc_attrs, asm_experimental_arch, c_variadic, allocator_api)]
#![allow(improper_ctypes, reason = "Rust lint false positive (Rust issue #115457)")]

// Re-export proc-macros
pub use pspsdk_macros::{export, exports, psp_stub};


pub mod sys;

#[cfg(target_os = "psp")]
#[cfg(feature = "non-stub-code")]
pub mod alloc;

#[doc(hidden)]
pub mod eabi;

mod private {
    pub trait Sealed {}

    impl Sealed for () {}
    impl Sealed for bool {}
    impl Sealed for u8 {}
    impl Sealed for i8 {}
    impl Sealed for u16 {}
    impl Sealed for i16 {}
    impl Sealed for u32 {}
    impl Sealed for i32 {}
    impl Sealed for usize {}
    impl Sealed for isize {}
    impl<T> Sealed for *const T {}
    impl<T> Sealed for *mut T {}
    impl<T> Sealed for &T {}
    impl<T> Sealed for &mut T {}
}


// Setup things
#[cfg(all(target_os = "psp", feature = "non-stub-code"))]
core::arch::global_asm!(
    r#"
        .section .lib.ent.top, "a", @progbits
        .align 2
        .word 0
    .global __lib_ent_top
    __lib_ent_top:
        .section .lib.ent.btm, "a", @progbits
        .align 2
    .global __lib_ent_bottom
    __lib_ent_bottom:
        .word 0

        .section .lib.stub.top, "a", @progbits
        .align 2
        .word 0
    .global __lib_stub_top
    __lib_stub_top:
        .section .lib.stub.btm, "a", @progbits
        .align 2
    .global __lib_stub_bottom
    __lib_stub_bottom:
        .word 0
    "#
);

#[doc(hidden)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub struct Align16<T>(pub T);

#[cfg(feature = "std")]
extern "C" {
    #[link_name = "main"]
    #[doc(hidden)]
    pub fn c_main(argc: isize, argv: *const *const u8) -> isize;
}

// Because code generated by `module!()` lives in user's crate, cfg attribute cannot be used there.
// Hence this macro.
#[cfg(feature = "std")]
#[doc(hidden)]
#[macro_export]
macro_rules! _start {
    ($_:expr, $argc:expr, $argv:expr) => {
        ::core::mem::tranmute(unsafe { $crate::c_main($argc as _, $argv as _) as _ })
    };
}
#[cfg(not(feature = "std"))]
#[doc(hidden)]
#[macro_export]
macro_rules! _start {
    ($psp_main:expr, $argc:expr, $argv:expr) => {{
        unsafe fn init_cwd(arg0: *mut u8) {
            let mut len = 0;
            while *arg0.add(len) != 0 {
                len += 1;
            }

            // Truncate until last '/'
            while len > 0 && *arg0.add(len - 1) != b'/' {
                len -= 1;
            }

            if len > 0 {
                let tmp = *arg0.add(len);
                *arg0.add(len) = 0;
                $crate::sys::io::sceIoChdir(arg0 as *const u8);
                *arg0.add(len) = tmp;
            }
        }

        if $argc > 0 {
            unsafe { init_cwd($argv as *mut u8) };
        }

        // TODO: Maybe print any error to debug screen?
        // let _ = $crate::catch_unwind($psp_main);
        let _ = $psp_main();

        $crate::sys::SceResult::new(0)
    }};
}

/// Declare a PSP module info.
///
/// This **does not** include basic `syslib`` export like [`module`].
#[macro_export]
macro_rules! module_info {
    ($name:expr, $version_major:expr, $version_minor:expr) => {
        #[used]
        #[unsafe(no_mangle)]
        #[unsafe(link_section = ".rodata.sceModuleInfo")]
        static module_info: $crate::Align16<$crate::sys::library::ModuleInfo> =
            $crate::Align16($crate::sys::library::ModuleInfo {
                attributes: $crate::sys::library::ModuleAttributes::from_bits_retain(0),
                version: ($version_major, $version_minor),
                name: $crate::sys::library::ModuleInfo::name_from_str($name),
                terminal_char: b'\0',
                gp: unsafe { (&raw const _gp).cast_mut().cast() },
                stub_top: unsafe { (&raw const __lib_stub_top).cast_mut().cast() },
                stub_end: unsafe { (&raw const __lib_stub_bottom).cast_mut().cast() },
                entry_top: unsafe { (&raw const __lib_ent_top).cast_mut().cast() },
                entry_end: unsafe { (&raw const __lib_ent_bottom).cast_mut().cast() },
            });

        unsafe extern "C" {
            static _gp: u8;
            static __lib_ent_bottom: u8;
            static __lib_ent_top: u8;
            static __lib_stub_bottom: u8;
            static __lib_stub_top: u8;
        }
    };
}

/// Declare a PSP module.
///
/// You must also define a `fn psp_main() { ... }` function in conjunction with
/// this macro.
///
/// Compat with `psp-rs`
#[macro_export]
macro_rules! module {
    ($name:expr, $version_major:expr, $version_minor:expr) => {
        #[doc(hidden)]
        mod __psp_module {
            $crate::module_info!($name, $version_major, $version_minor);

            #[unsafe(no_mangle)]
            extern "C" fn module_start(argc_bytes: usize, argv: *mut ::core::ffi::c_void) -> isize {
                extern "C" fn main_thread(
                    argc: usize, argv: *mut ::core::ffi::c_void,
                ) -> $crate::sys::SceResult<u32> {
                    $crate::_start!(super::psp_main, argc, argv)
                }

                unsafe {
                    let Ok(id) = $crate::sys::thread::sceKernelCreateThread(
                        c"main_thread".as_ptr().cast(),
                        main_thread,
                        // default priority of 32.
                        32,
                        // 256kb stack
                        256 * 1024,
                        $crate::sys::thread::ThreadAttributes::UserMode
                            | $crate::sys::thread::ThreadAttributes::UseVFPU,
                        None,
                    )
                    .into_result() else {
                        return -1;
                    };

                    $crate::sys::thread::sceKernelStartThread(id, argc_bytes, argv);
                }

                0
            }

            $crate::exports! {
                "syslib", 0, 0, 0x8000, [
                    fn module_start,
                    static module_info,
                ];
            }
        }
    };
}
