/// Prints to the PSP screen.
#[macro_export]
#[cfg(feature = "non-stub-code")]
macro_rules! dprint {
    ($($arg:tt)*) => {{
        $crate::io::printing::_dprint(::core::format_args!($($arg)*));
    }};
}

/// Prints to the PSP screen, with a newline.
#[macro_export]
#[cfg(feature = "non-stub-code")]
macro_rules! dprintln {
    () => {
        $crate::dprint!("\n")
    };
    ($($arg:tt)*) => {{
        $crate::dprint!("{}\n", ::core::format_args!($($arg)*));
    }};
}

/// Prints to the PSP stdout.
#[macro_export]
#[cfg(feature = "non-stub-code")]
macro_rules! print {
    ($($arg:tt)*) => {{
        $crate::io::printing::_print(::core::format_args!($($arg)*));
    }};
}

/// Prints to the PSP stdout, with a newline.
#[macro_export]
#[cfg(feature = "non-stub-code")]
macro_rules! println {
    () => {
        $crate::print!("\n")
    };
    ($($arg:tt)*) => {{
        $crate::print!("{}\n", ::core::format_args!($($arg)*));
    }};
}

/// Prints to the PSP stderr.
#[macro_export]
#[cfg(feature = "non-stub-code")]
macro_rules! eprint {
    ($($arg:tt)*) => {{
        $crate::io::printing::_eprint(::core::format_args!($($arg)*));
    }};
}

/// Prints to the PSP stderr, with a newline.
#[macro_export]
#[cfg(feature = "non-stub-code")]
macro_rules! eprintln {
    () => {
        $crate::eprint!("\n")
    };
    ($($arg:tt)*) => {{
        $crate::eprint!("{}\n", ::core::format_args!($($arg)*));
    }};
}


// Because code generated by `module!()` lives in user's crate, cfg attribute cannot be used there.
// Hence this macro.
#[cfg(feature = "std")]
#[doc(hidden)]
#[macro_export]
macro_rules! _start {
    ($_:expr, $argc:expr, $argv:expr) => {
        unsafe { ::core::mem::transmute(unsafe { $crate::c_main($argc as _, $argv as _) as _ }) }
    };
}
#[cfg(not(feature = "std"))]
#[doc(hidden)]
#[macro_export]
macro_rules! _start {
    ($psp_main:expr, $argc:expr, $argv:expr) => {{
        unsafe fn init_cwd(arg0: *mut u8) {
            let mut len = 0;
            while *arg0.add(len) != 0 {
                len += 1;
            }

            // Truncate until last '/'
            while len > 0 && *arg0.add(len - 1) != b'/' {
                len -= 1;
            }

            if len > 0 {
                let tmp = *arg0.add(len);
                *arg0.add(len) = 0;
                let _res = $crate::sys::io::sceIoChdir(arg0 as *const u8);
                *arg0.add(len) = tmp;
            }
        }

        if $argc > 0 {
            unsafe { init_cwd($argv as *mut u8) };
        }

        // TODO: Maybe print any error to debug screen?
        #[cfg(panic = "unwind")]
        {
            let _ = $crate::panic::catch_unwind($psp_main);
        }

        #[cfg(panic = "abort")]
        {
            let _ = $psp_main();
        }
        // let _ = $psp_main();

        $crate::cleanup();

        $crate::sys::SceResult::new(0)
    }};
}

/// Declare a PSP module info.
///
/// This **does not** include basic `syslib` export like [`module`].
#[macro_export]
macro_rules! module_info {
    ($name:expr, $version_major:expr, $version_minor:expr) => {
        $crate::module_info!(
            $name,
            $version_major,
            $version_minor,
            $crate::sys::library::ModuleAttributes::base_default()
        );
    };

    ($name:expr, $version_major:expr, $version_minor:expr, $attr:expr) => {
        #[used]
        #[unsafe(no_mangle)]
        #[unsafe(link_section = ".rodata.sceModuleInfo")]
        static module_info: $crate::Align16<$crate::sys::library::ModuleInfo> =
            $crate::Align16($crate::sys::library::ModuleInfo {
                attributes: $attr,
                version: ($version_major, $version_minor),
                name: $crate::sys::library::ModuleInfo::name_from_str($name),
                terminal_char: b'\0',
                gp: unsafe { &_gp },
                stub_top: unsafe { &__lib_stub_top },
                stub_end: unsafe { &__lib_stub_bottom },
                entry_top: unsafe { &__lib_ent_top },
                entry_end: unsafe { &__lib_ent_bottom },
            });

        unsafe extern "C" {
            static _gp: u8;
            static __lib_ent_bottom: u8;
            static __lib_ent_top: u8;
            static __lib_stub_bottom: u8;
            static __lib_stub_top: u8;
        }
    };
}

/// Declare a PSP module.
///
/// You must also define a `fn psp_main() { ... }` function in conjunction with
/// this macro.
///
/// Compat with `psp-rs`
#[macro_export]
macro_rules! module {
    ($name:expr, $version_major:expr, $version_minor:expr) => {
        #[doc(hidden)]
        mod __psp_module {
            $crate::module_info!($name, $version_major, $version_minor);

            #[unsafe(no_mangle)]
            extern "C" fn module_start(argc_bytes: usize, argv: *mut ::core::ffi::c_void) -> isize {
                extern "C" fn main_thread(
                    argc: usize, argv: *mut ::core::ffi::c_void,
                ) -> $crate::sys::SceResult<u32> {
                    $crate::_start!(super::psp_main, argc, argv)
                }

                $crate::set_psp_os_functions();
                unsafe {
                    let Ok(id) = $crate::sys::thread::sceKernelCreateThread(
                        c"main_thread".as_ptr().cast(),
                        main_thread,
                        // default priority of 32.
                        32,
                        // 256kb stack
                        256 * 1024,
                        $crate::sys::thread::ThreadAttributes::UserMode
                            | $crate::sys::thread::ThreadAttributes::UseVFPU,
                        None,
                    )
                    .into_result() else {
                        return -1;
                    };

                    let _res = $crate::sys::thread::sceKernelStartThread(id, argc_bytes, argv);
                }

                0
            }

            $crate::exports! {
                "syslib", $version_major, $version_minor, 0x8000, [
                    fn module_start,
                    static module_info.0 : 0xF01D73A7,
                ];
            }
        }
    };
}
