name: Check

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
      - .gitignore
  pull_request:
    paths-ignore:
      - "**.md"
      - "**/LICENSE"
      - .github/FUNDING.yml
      - .editorconfig
      - .gitignore

jobs:
  check:
    name: Check and Test
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     toolchain: ["nightly"]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v7
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        # toolchain: ${{ matrix.toolchain }}
        toolchain: "nightly"
        components: rust-src
    - name: Cache cargo output
      uses: Swatinem/rust-cache@v2
    - name: Check and install cargo-pspbuild
      run: cargo install --locked --path ./cargo-pspbuild --force
    - name: Check user
      run: cargo check --target=mipsel-sony-psp -Zbuild-std=core,alloc,compiler_builtins,panic_unwind,panic_abort
    - name: Check kernel
      run: cargo check --target=mipsel-sony-psp --features=kernel -Zbuild-std=core,alloc,compiler_builtins,panic_unwind,panic_abort
    - name: Check Examples (release with unwind)
      run: ./examples/run_all.sh
    - name: Build tests
      run: |
        cd tests/unit/
        cargo pspbuild --target-dir=../../target/
        cd ../..
    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: psp-ci-test
        path: target/mipsel-sony-psp/debug/pspsdk-unit-tests.EBOOT.PBP

  run-tests:
    needs: check
    runs-on: ubuntu-latest
    container: grayjack1/ppsspp-headless:latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: psp-ci-test
      - name: Run Tests
        shell: bash
        run: |
          set -euo pipefail
          /ppsspp/build-sdl/PPSSPPHeadless --graphics=software ./pspsdk-unit-tests.EBOOT.PBP --timeout=10 -r . > psp_output_file.log
          cat psp_output_file.log
          if [ "$(tail -n 1 psp_output_file.log)" = "FINAL_SUCCESS" ]; then
              echo Test passed
          else
              echo Test failed
              exit 1
          fi
